const Chapters = [

    { "name": "EO Adelaide" },
    { "name": "EO Albany" },
    { "name": "EO Andhra Pradesh" },
    { "name": "EO APAC Bridge" },
    { "name": "EO Argentina" },
    { "name": "EO Arizona" },
    { "name": "EO At Large" },
    { "name": "EO Atlanta" },
    { "name": "EO Atlantic Canada" },
    { "name": "EO Austin" },
    { "name": "EO Austria - Coming Soon" },
    { "name": "EO Bahrain" },
    { "name": "EO Bali - Coming Soon" },
    { "name": "EO Baltimore" },
    { "name": "EO Bangalore" },
    { "name": "EO Bangkok Metropolitan" },
    { "name": "EO Bangladesh" },
    { "name": "EO Barcelona" },
    { "name": "EO Beijing" },
    { "name": "EO Beijing Metropolitan" },
    { "name": "EO Belgium" },
    { "name": "EO Berlin" },
    { "name": "EO Bhopal" },
    { "name": "EO Birmingham" },
    { "name": "EO Bogota" },
    { "name": "EO Boston" },
    { "name": "EO Bryan-College Station" },
    { "name": "EO Cairo" },
    { "name": "EO Calgary" },
    { "name": "EO Canada Bridge" },
    { "name": "EO Cancun-Riviera Maya" },
    { "name": "EO Cape Town" },
    { "name": "EO Charleston" },
    { "name": "EO Charlotte" },
    { "name": "EO Chengdu" },
    { "name": "EO Chennai" },
    { "name": "EO Chicago" },
    { "name": "EO China East" },
    { "name": "EO Cincinnati" },
    { "name": "EO Cleveland" },
    { "name": "EO Coimbatore" },
    { "name": "EO Colorado" },
    { "name": "EO Columbus" },
    { "name": "EO Connecticut" },
    { "name": "EO Costa Rica" },
    { "name": "EO Dalian" },
    { "name": "EO Dallas" },
    { "name": "EO DC" },
    { "name": "EO Detroit" },
    { "name": "EO Dominican Republic" },
    { "name": "EO Dubai" },
    { "name": "EO Durban" },
    { "name": "EO Edmonton" },
    { "name": "EO El Salvador" },
    { "name": "EO Europe Bridge" },
    { "name": "EO Fort Worth" },
    { "name": "EO Germany - Rhine Ruhr" },
    { "name": "EO Germany - Southwest" },
    { "name": "EO Goa" },
    { "name": "EO Greater Bay Metropolitan" },
    { "name": "EO Greater China Bridge" },
    { "name": "EO Greece" },
    { "name": "EO Guadalajara" },
    { "name": "EO Guangzhou" },
    { "name": "EO Guatemala" },
    { "name": "EO Guayaquil" },
    { "name": "EO Gujarat" },
    { "name": "EO Gurgaon" },
    { "name": "EO Hainan" },
    { "name": "EO Hamburg" },
    { "name": "EO Hawaii" },
    { "name": "EO Hokkaido" },
    { "name": "EO Hokuriku" },
    { "name": "EO Hong Kong" },
    { "name": "EO Houston" },
    { "name": "EO Hyderabad" },
    { "name": "EO Ibaraki" },
    { "name": "EO Idaho" },
    { "name": "EO Indianapolis" },
    { "name": "EO Indonesia" },
    { "name": "EO Indonesia East" },
    { "name": "EO Indore" },
    { "name": "EO Inland Empire" },
    { "name": "EO Iowa" },
    { "name": "EO Ireland" },
    { "name": "EO Islamabad" },
    { "name": "EO Israel" },
    { "name": "EO Italy" },
    { "name": "EO Jaipur" },
    { "name": "EO Jammu and Kashmir - Coming Soon" },
    { "name": "EO Japan Korea Bridge" },
    { "name": "EO Jeddah" },
    { "name": "EO Johannesburg" },
    { "name": "EO Jordan" },
    { "name": "EO Kanagawa Coming Soon" },
    { "name": "EO Kansas City" },
    { "name": "EO Karachi" },
    { "name": "EO Kenya" },
    { "name": "EO Kerala" },
    { "name": "EO Kobe" },
    { "name": "EO Kolkata" },
    { "name": "EO Korea" },
    { "name": "EO Kuwait" },
    { "name": "EO Kyoto" },
    { "name": "EO Kyushu" },
    { "name": "EO LAC Bridge" },
    { "name": "EO Lahore" },
    { "name": "EO Las Vegas" },
    { "name": "EO Lebanon" },
    { "name": "EO Los Angeles" },
    { "name": "EO Los Angeles - Valley" },
    { "name": "EO Louisiana" },
    { "name": "EO Madrid" },
    { "name": "EO Malaysia" },
    { "name": "EO Melbourne" },
    { "name": "EO MEPA Bridge" },
    { "name": "EO Merida - Coming Soon" },
    { "name": "EO Mexico City" },
    { "name": "EO Minnesota" },
    { "name": "EO Monterrey" },
    { "name": "EO Montreal" },
    { "name": "EO Morocco - Coming Soon" },
    { "name": "EO Mumbai" },
    { "name": "EO Munich" },
    { "name": "EO Nagoya" },
    { "name": "EO Nagpur" },
    { "name": "EO Nashville" },
    { "name": "EO Navi Mumbai" },
    { "name": "EO Nebraska" },
    { "name": "EO Nepal" },
    { "name": "EO Netherlands" },
    { "name": "EO New Delhi" },
    { "name": "EO New Jersey" },
    { "name": "EO New York" },
    { "name": "EO New Zealand" },
    { "name": "EO Nicaragua" },
    { "name": "EO Noida" },
    { "name": "EO North Japan" },
    { "name": "EO North Karnataka" },
    { "name": "EO Northeast India" },
    { "name": "EO NY Long Island" },
    { "name": "EO Odisha" },
    { "name": "EO Okanagan" },
    { "name": "EO Okinawa" },
    { "name": "EO Oklahoma City" },
    { "name": "EO Oman" },
    { "name": "EO Orange County" },
    { "name": "EO Osaka" },
    { "name": "EO Ottawa" },
    { "name": "EO Panama" },
    { "name": "EO Paraná-Santa Catarina" },
    { "name": "EO Paris" },
    { "name": "EO Perth" },
    { "name": "EO Peru" },
    { "name": "EO Philadelphia" },
    { "name": "EO Philippines" },
    { "name": "EO Philippines South" },
    { "name": "EO Pittsburgh" },
    { "name": "EO Poland" },
    { "name": "EO Portland" },
    { "name": "EO Porto Alegre" },
    { "name": "EO Portugal" },
    { "name": "EO Puerto Rico" },
    { "name": "EO Pune" },
    { "name": "EO Punjab" },
    { "name": "EO Quebec" },
    { "name": "EO Queensland" },
    { "name": "EO Queretaro" },
    { "name": "EO Quito" },
    { "name": "EO Raipur" },
    { "name": "EO Raleigh Durham" },
    { "name": "EO Ranchi" },
    { "name": "EO Reno Tahoe" },
    { "name": "EO Richmond" },
    { "name": "EO Rio De Janeiro" },
    { "name": "EO Riyadh" },
    { "name": "EO Russia" },
    { "name": "EO Sacramento" },
    { "name": "EO Saint Petersburg" },
    { "name": "EO San Antonio" },
    { "name": "EO San Diego" },
    { "name": "EO San Francisco" },
    { "name": "EO San Francisco East Bay" },
    { "name": "EO Sao Paulo" },
    { "name": "EO Saskatoon" },
    { "name": "EO Saudi East" },
    { "name": "EO Seattle" },
    { "name": "EO Setouchi" },
    { "name": "EO Shanghai" },
    { "name": "EO Shenyang - Coming Soon" },
    { "name": "EO Shenzhen" },
    { "name": "EO Silicon Valley" },
    { "name": "EO Singapore" },
    { "name": "EO South Asia Bridge" },
    { "name": "EO South Asia Platinum Bridge" },
    { "name": "EO South East Europe" },
    { "name": "EO South Florida" },
    { "name": "EO Southeast Virginia" },
    { "name": "EO Southwest Ontario" },
    { "name": "EO Sri Lanka" },
    { "name": "EO St. Louis" },
    { "name": "EO Suisse Romande" },
    { "name": "EO Surat" },
    { "name": "EO Sweden - Coming Soon" },
    { "name": "EO Sydney" },
    { "name": "EO Taipei" },
    { "name": "EO Tampa Bay" },
    { "name": "EO Tanzania" },
    { "name": "EO Thailand" },
    { "name": "EO Tokyo Central" },
    { "name": "EO Tokyo Metropolitan" },
    { "name": "EO Tokyo Platinum" },
    { "name": "EO Tokyo West" },
    { "name": "EO Toronto" },
    { "name": "EO Toronto Plus" },
    { "name": "EO Tulsa" },
    { "name": "EO Turkey" },
    { "name": "EO Uganda" },
    { "name": "EO UK - London" },
    { "name": "EO Ukraine - Coming Soon" },
    { "name": "EO US Central Bridge" },
    { "name": "EO US East Bridge" },
    { "name": "EO US West Bridge" },
    { "name": "EO Utah" },
    { "name": "EO Uttar Pradesh" },
    { "name": "EO Vancouver" },
    { "name": "EO Vancouver Island" },
    { "name": "EO Vietnam" },
    { "name": "EO West Michigan" },
    { "name": "EO Western New York" },
    { "name": "EO Winnipeg" },
    { "name": "EO Wisconsin" },
    { "name": "EO Zurich" },
]

export default Chapters;